services:
  - type: web
    name: ubuntu-math-backend
    env: node
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLEANUP_SECRET
        sync: false
      - key: EVRIPAY_API_URL
        value: https://evripay.onrender.com
      - key: EVRIPAY_CLIENT_ID
        sync: false
      - key: EVRIPAY_API_KEY
        sync: false
      - key: EVRIPAY_WEBHOOK_SECRET
        sync: false
