import { Request, Response } from 'express';
import Course from '../models/Course';
export const getCourses = async (req: Request, res: Response) => { try { const courses = await Course.find({ published: true }); res.json(courses); } catch (err) { res.status(500).json({ message: 'Failed to fetch courses', error: err }); } };
export const getAllCourses = async (req: Request, res: Response) => { try { const courses = await Course.find({}); res.json(courses); } catch (err) { res.status(500).json({ message: 'Failed to fetch courses', error: err }); } };
export const getCourseById = async (req: Request, res: Response) => { try { const course = await Course.findById(req.params.id); if (!course) return res.status(404).json({ message: 'Course not found' }); res.json(course); } catch (err) { res.status(500).json({ message: 'Failed to fetch course', error: err }); } };
export const getCourseBySlug = async (req: Request, res: Response) => { try { const course = await Course.findOne({ slug: req.params.slug }); if (!course) return res.status(404).json({ message: 'Course not found' }); res.json(course); } catch (err) { res.status(500).json({ message: 'Failed to fetch course', error: err }); } };
export const createCourse = async (req: Request, res: Response) => { try { const course = await Course.create(req.body); res.status(201).json(course); } catch (err) { res.status(500).json({ message: 'Failed to create course', error: err }); } };
export const updateCourse = async (req: Request, res: Response) => { try { const course = await Course.findByIdAndUpdate(req.params.id, req.body, { new: true }); if (!course) return res.status(404).json({ message: 'Course not found' }); res.json(course); } catch (err) { res.status(500).json({ message: 'Failed to update course', error: err }); } };
export const deleteCourse = async (req: Request, res: Response) => { try { await Course.findByIdAndDelete(req.params.id); res.json({ message: 'Course deleted' }); } catch (err) { res.status(500).json({ message: 'Failed to delete course', error: err }); } };
