import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import apiRoutes from './routes/api';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;
const MONGODB_URI = process.env.MONGODB_URI || '';
app.use(cors({ origin: ['https://ubuntu-math-frontend.vercel.app','https://ubuntu-math-frontend.onrender.com','https://ubuntu-math.cams.org.za','http://localhost:5173','http://localhost:5000'], credentials: true }));
app.use(express.json());
app.use('/uploads', express.static(path.join(process.cwd(), 'uploads')));
app.get('/ping2', (_req, res) => res.send('pong2'));
app.use('/api', apiRoutes);
console.log('API routes mounted at /api');
mongoose.connect(MONGODB_URI).then(() => { console.log('Connected to MongoDB'); app.listen(PORT, () => console.log('Server running on port ' + PORT)); }).catch((err) => console.error('MongoDB connection error:', err));
export default app;
